export const wooKeys = [
  'ID',
  'Type',
  'SKU',
  'Name',
  'Published',
  'Is featured?',
  'Visibility in catalog',
  'Short description',
  'Description',
  'Date sale price starts',
  'Date sale price ends',
  'Tax status',
  'Tax class',
  'In stock?',
  'Stock',
  'Low stock amount',
  'Backorders allowed?',
  'Sold individually?',
  'Weight (lbs)',
  'Length (in)',
  'Width (in)',
  'Height (in)',
  'Allow customer reviews?',
  'Purchase note',
  'Sale price',
  'Regular price',
  'Categories',
  'Tags',
  'Shipping class',
  'Images',
  'Download limit',
  'Download expiry days',
  'Parent',
  'Grouped products',
  'Upsells',
  'Cross-sells',
  'External URL',
  'Button text',
  'Position',
  'Meta: _supplier_class'
];

export const tuckerKeys = [
  'Tucker Item',
  'Vendor Part',
  'OEM',
  'UPC',
  'Product Name',
  'DESC',
  'BRAND',
  'CATEGORY',
  'SEGMENT',
  'Dealer Price',
  'Peak Item Surcharge ',
  'Retail Price',
  'Sell UOM',
  'Retail UOM',
  'Retail Conversion F actor',
  'Map Policy',
  'Map Price',
  'Closeout/Discontinu ed Status',
  'Superceded To Item',
  'Ships From Supplier ',
  'SIZE',
  'WEIGHT',
  'DEPTH',
  'WIDTH',
  'HEIGHT',
  'Hazardous Flag',
  'OVERSIZE',
  'Drop Ship Freight C lass',
  'Tire Size',
  'Country of Origin',
  'Carb Restricted',
  'Proposition 65 Flag ',
  'Prop 65 Product War ning',
  'Copy Text',
  'Bullet Text',
  'Include Text',
  'TYPE',
  'STYLE',
  'COLOR',
  'Image Main',
  'Image Proxy',
  'Image Alternate 1',
  'Image Alternate 2',
  'Image Alternate 3',
  'Image Action 1',
  'Image Action 2',
  'Image Detail 1',
  'Image Detail 2'
];

export const wooKeysMap = {
  //   id: 'ID',
  type: 'Type',
  sku: 'SKU',
  name: 'Name',
  published: 'Published',
  is_featured: 'Is featured?',
  visibility_in_catalog: 'Visibility in catalog',
  short_description: 'Short description',
  description: 'Description',
  date_sale_price_starts: 'Date sale price starts',
  date_sale_price_ends: 'Date sale price ends',
  tax_status: 'Tax status',
  tax_class: 'Tax class',
  in_stock: 'In stock?',
  stock: 'Stock',
  low_stock_amount: 'Low stock amount',
  backorders_allowed: 'Backorders allowed?',
  sold_individually: 'Sold individually?',
  weight_lbs: 'Weight (lbs)',
  length_in: 'Length (in)',
  width_in: 'Width (in)',
  height_in: 'Height (in)',
  //   weight_kg: 'Weight (kg)',
  //   length_cm: 'Length (cm)',
  //   width_cm: 'Width (cm)',
  //   height_cm: 'Height (cm)',
  allow_customer_reviews: 'Allow customer reviews?',
  purchase_note: 'Purchase note',
  sale_price: 'Sale price',
  regular_price: 'Regular price',
  categories: 'Categories',
  tags: 'Tags',
  shipping_class: 'Shipping class',
  images: 'Images',
  download_limit: 'Download limit',
  download_expiry_days: 'Download expiry days',
  parent: 'Parent',
  grouped_products: 'Grouped products',
  upsells: 'Upsells',
  cross_sells: 'Cross-sells',
  external_url: 'External URL',
  button_text: 'Button text',
  position: 'Position',
  meta_supplier_class: 'Meta: _supplier_class'
  //   attribute_1_name: 'Attribute 1 name',
  //   attribute_1_values: 'Attribute 1 value(s)',
  //   attribute_1_visible: 'Attribute 1 visible',
  //   attribute_1_global: 'Attribute 1 global',
  //   meta_wpcom_is_markdown: 'Meta: _wpcom_is_markdown',
  //   meta_site_sidebar_layout: 'Meta: site-sidebar-layout',
  //   meta_site_content_layout: 'Meta: site-content-layout',
  //   meta_theme_transparent_header_meta: 'Meta: theme-transparent-header-meta',
  //   meta_yoast_wpseo_content_score: 'Meta: _yoast_wpseo_content_score',
  //   meta_yoast_wpseo_estimated_reading_time_minutes: 'Meta: _yoast_wpseo_estimated-reading-time-minutes',
  //   meta_yoast_wpseo_wordproof_timestamp: 'Meta: _yoast_wpseo_wordproof_timestamp',
  //   attribute_2_name: 'Attribute 2 name',
  //   attribute_2_values: 'Attribute 2 value(s)',
  //   attribute_2_visible: 'Attribute 2 visible',
  //   attribute_2_global: 'Attribute 2 global',
  //   meta_subscription_period: 'Meta: _subscription_period',
  //   meta_subscription_period_interval: 'Meta: _subscription_period_interval',
  //   meta_subscription_length: 'Meta: _subscription_length',
  //   meta_subscription_trial_period: 'Meta: _subscription_trial_period',
  //   meta_subscription_payment_sync_date: 'Meta: _subscription_payment_sync_date'
};

export const tuckerKeysMap = {
  tucker_item: '"Tucker Item"',
  vendor_part: '"Vendor Part"',
  oem: 'OEM',
  upc: 'UPC',
  product_name: '"Product Name"',
  desc: 'DESC',
  brand: 'BRAND',
  category: 'CATEGORY',
  segment: 'SEGMENT',
  dealer_price: '"Dealer Price"',
  peak_item_surcharge: '"Peak Item Surcharge "',
  retail_price: '"Retail Price"',
  sell_uom: '"Sell UOM"',
  retail_uom: '"Retail UOM"',
  retail_conversion_f_actor: '"Retail Conversion F actor"',
  map_policy: '"Map Policy"',
  map_price: '"Map Price"',
  closeoutdiscontinu_ed_status: '"Closeout/Discontinu ed Status"',
  superceded_to_item: '"Superceded To Item"',
  ships_from_supplier: '"Ships From Supplier "',
  size: 'SIZE',
  weight: 'WEIGHT',
  depth: 'DEPTH',
  width: 'WIDTH',
  height: 'HEIGHT',
  hazardous_flag: '"Hazardous Flag"',
  oversize: 'OVERSIZE',
  drop_ship_freight_c_lass: '"Drop Ship Freight C lass"',
  tire_size: '"Tire Size"',
  country_of_origin: '"Country of Origin"',
  carb_restricted: '"Carb Restricted"',
  proposition_65_flag: '"Proposition 65 Flag "',
  prop_65_product_war_ning: '"Prop 65 Product War ning"',
  copy_text: '"Copy Text"',
  bullet_text: '"Bullet Text"',
  include_text: '"Include Text"',
  type: 'TYPE',
  style: 'STYLE',
  color: 'COLOR',
  image_main: '"Image Main"',
  image_proxy: '"Image Proxy"',
  image_alternate_1: '"Image Alternate 1"',
  image_alternate_2: '"Image Alternate 2"',
  image_alternate_3: '"Image Alternate 3"',
  image_action_1: '"Image Action 1"',
  image_action_2: '"Image Action 2"',
  image_detail_1: '"Image Detail 1"',
  image_detail_2: '"Image Detail 2"'
};

export const wooRowDefaults = {
  Published: 1,
  'Is featured?': 0,
  'Visibility in catalog': 'visible',
  'Short description': '',
  Description: '',
  'Date sale price starts': '',
  'Date sale price ends': '',
  'Tax status': 'taxable',
  // 'Tax class': 'parent',
  'In stock?': 1,
  Stock: 10,
  'Low stock amount': 2,
  'Backorders allowed?': 0,
  'Sold individually?': 0,
  // 'Weight (kg)',
  // 'Length (cm)',
  // 'Width (cm)',
  // 'Height (cm)',
  // 'Allow customer reviews?',
  'Purchase note': '',
  'Sale price': '',
  // 'Regular price',
  // 'Categories',
  Tags: '',
  'Shipping class': '',
  // 'Images':'',
  'Download limit': '',
  'Download expiry days': '',
  Parent: '',
  'Grouped products': '',
  Upsells: '',
  'Cross-sells': '',
  'External URL': '',
  'Button text': '',
  Position: 0,
  'Meta: _supplier_class': 'WooDropship\\Suppliers\\Tucker'
  // 'Attribute 1 name',
  // 'Attribute 1 value(s)',
  // 'Attribute 1 visible',
  // 'Attribute 1 global',
  // 'Meta: _wpcom_is_markdown',
  // 'Meta: site-sidebar-layout',
  // 'Meta: site-content-layout',
  // 'Meta: theme-transparent-header-meta',
  // 'Meta: _yoast_wpseo_content_score',
  // 'Meta: _yoast_wpseo_estimated-reading-time-minutes',
  // 'Meta: _yoast_wpseo_wordproof_timestamp',
  // 'Attribute 2 name',
  // 'Attribute 2 value(s)',
  // 'Attribute 2 visible',
  // 'Attribute 2 global',
  // 'Meta: _subscription_period',
  // 'Meta: _subscription_period_interval',
  // 'Meta: _subscription_length',
  // 'Meta: _subscription_trial_period',
  // 'Meta: _subscription_payment_sync_date'
};

// export function getWooDefaults(product) {
//   const isVariation = product.config.type === 'variation';
//   return {
//     'Tax class': isVariation ? 'parent' : '',
//     'Allow customer reviews?': isVariation ? 0 : 1
//   };
// }
